config/routes.rb
Popup::Application.routes.draw do

 
  get "/index/signup"
  
  root :to => "index#home"
 
  devise_for :users
 
  match "/tab", :to => "index#tab"
  match "/jquery_signup", :to => "index#jquery_signup"

  
  match "/image_test", :to => "index#image_test"
  match "/image_1", :to => "index#image_1"
  match "/image_3", :to => "index#image_3"
 

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :zip, :designer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

def home
	
end

def tab
	respond_to do |format|
		format.js {render :layout => false}
	end
end

def jquery_signup
	respond_to do |format|
		format.js {render :layout => false}
	end
end

def image_1
	respond_to do |format|
		format.js {render :layout => false}
	end
end

def image_test
respond_to do |format|
		format.js {render :layout => false}
	end
end

def image_3
	respond_to do |format|
		format.js {render :layout => false}
	end
end



end

app/helpers/application_helper.rb
module ApplicationHelper


  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

 
  def devise_error_messages!
    
  end


end

app/helpers/index_helper.rb
module IndexHelper

end

app/views/index/_image_desc.html.erb
<%=link_to "X", :action=> "home"%>

<h1>Coming Soon !!!</h1>

app/views/index/_image_test.html.erb
<%=link_to "X", :action=> "home"%>

<h1>
Test Test Test
</h1>

<%=image_tag "rails.png"%>

app/views/index/_image_text.html.erb
<%=link_to "X", :action=> "home"%>

<h1> lorum impsum lorum impsum lorum impsum lorum impsum</h1>

<%=link_to "Know More", :action => "home"%>

app/views/index/_signup.html.erb
<%=link_to "X", :action=> "home"%>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <%= f.fields_for :profile do |builder|%>
            <p>
                <%=builder.label :zip, "Zip Code"%> <br />
                <%=builder.text_field :zip%>
            </p>

            <%end%>
            <p>
                <%= f.label :designer %>

                <%= f.check_box :designer %></p>

            </p>

  <div><%= f.submit "Sign up" %></div>
<% end %>

<%= render :partial => "devise/shared/links" %>

app/views/index/_test.html.erb
<%=link_to "X", :action=> "home"%>
  
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

<%= render :partial => "devise/shared/links" %>

app/views/index/home.html.erb
<%=image_tag "tajmahal.jpg"%> 
<%=link_to "click here", image_1_path, :remote => true, :class => "button"%>


<%=image_tag "india.jpg"%>
<%=link_to "click here", image_3_path, :remote => true, :class => "button"%>

<%=image_tag "charminar.jpg"%>
<%=link_to "click here", image_test_path, :remote => true, :class => "button"%>

<% if user_signed_in? %>  
    Signed in as <%= current_user.email %> <br />
<%= link_to "Sign out", destroy_user_session_path,:method => :delete , :class => "button rights"%> <br />
	<%else%>
<%=link_to "Sign Up", jquery_signup_path,:remote => true, :class => "button rights"%> 
<%=link_to "Sign In", tab_path, :remote => true, :class => "button rights"%> 
<%end%>


<div class="popupContact"></div>
 
<div id="backgroundPopup"></div> 

app/views/index/image_1.js.erb
$( ".popupContact" ).html( "<%= escape_javascript( render( :partial => "image_text") ) %>" );

app/views/index/image_3.js.erb
$( ".popupContact" ).html( "<%= escape_javascript( render( :partial => "image_desc") ) %>" );

app/views/index/image_test.js.erb
$( ".popupContact" ).html( "<%= escape_javascript( render( :partial => "image_test") ) %>" );

app/views/index/jquery_signup.js.erb
$( ".popupContact" ).html( "<%= escape_javascript( render( :partial => "signup") ) %>" );

app/views/index/tab.js.erb
$( ".popupContact" ).html( "<%= escape_javascript( render( :partial => "test") ) %>" );

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Popup</title>
  <%= stylesheet_link_tag :all %>
  <%=javascript_include_tag :defaults%>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "popup"%>
  
  <%= csrf_meta_tag %>
</head>
<body>
<p class="notice"> <%=notice%> </p>
<p class="alert"> <%=alert%> </p>
<%= yield %>

</body>
</html>